name: UACM Blockchain Smart Contract CI

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: chaincode

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Descargar dependencias
        run: |
          go mod download
          go mod tidy

      - name: Compilar chaincode
        run: go build -v ./...

      - name: Verificar formato
        run: |
          FILES=$(find . \
            -path "./vendor" -prune -o \
            -name "*.go" -print | xargs gofmt -l)
      
          if [ -n "$FILES" ]; then
            echo "Los siguientes archivos requieren gofmt:"
            echo "$FILES"
            exit 1
          fi

      - name: Ejecutar pruebas
        run: go test -v ./...
